/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ../public/Model1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Model1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.723, 12.17, -3.627]} scale={[1.878, 1.16, 1.878]}>
        <spotLight intensity={1} angle={0.373} penumbra={0.15} decay={2} color="#fff8e2" rotation={[0, 0, 0]} />
      </group>
      <group position={[-7.724, 12.244, -16.234]}>
        <spotLight intensity={1} angle={Math.PI / 8} penumbra={0.15} decay={2} rotation={[0, 0, 0]} position={[0, 0, 0]}/>
      </group>
      <group position={[6.914, 12.063, -16.756]}>
        <spotLight intensity={1} angle={Math.PI / 8} penumbra={0.15} decay={2} rotation={[0, 0, 0]} />
      </group>
      <group position={[-12.088, 0.736, -17.964]} scale={[4.678, 4.832, 5.123]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.door} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.bed1} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.bed} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.toilet} position={[5.135, 1.127, -20.145]} scale={[0.894, 0.74, 0.903]} />
      <mesh geometry={nodes.fan.geometry} material={materials.fan} position={[8.819, 9.283, -22.805]} scale={0.967} />
      <mesh geometry={nodes.Circle.geometry} material={materials.fan} position={[8.793, 9.288, -22.976]} rotation={[Math.PI / 2, 0, 0]} scale={1.687} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.floor1} position={[18.606, 0, -9.193]} rotation={[0, Math.PI / 2, 0]} scale={[1, 1, -0.251]} />
      <mesh geometry={nodes.wall.geometry} material={materials.floor} position={[-1.204, 6.243, 5.765]} />
      <mesh geometry={nodes.doorLiving.geometry} material={materials.door} position={[3.306, 8.323, 3.889]} />
      <mesh geometry={nodes.doorBath.geometry} material={materials.door} position={[-3.98, 8.319, -12.261]} />
      <mesh geometry={nodes.doorBed.geometry} material={materials.door} position={[-9.854, 8.323, -12.332]} />
      <mesh geometry={nodes.sofa.geometry} material={materials.sofa} position={[2.25, 1.185, -1.387]} />
      <group position={[-11.368, 3.542, -6.087]} scale={0.074}>
        <mesh geometry={nodes.Cube.geometry} material={materials.kitchen4} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.kitchen2} />
      </group>
      <group position={[-11.516, 1.647, -2.81]} scale={0.071}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.kitchen4} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.kitchen1} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials.kitchen} />
      </group>
      <mesh geometry={nodes.fence.geometry} material={materials.wood} position={[14.54, 1.304, -23.696]} rotation={[Math.PI / 2, 0, 3.107]} scale={[0.573, 1, 1.304]} />
      <mesh geometry={nodes.lightBed.geometry} material={materials.lightbulb} position={[-7.999, 11.487, -16.31]} scale={[1.883, 0.999, 1.883]} />
      <mesh geometry={nodes.LightBath.geometry} material={materials.lightbulb} position={[6.774, 11.487, -16.31]} scale={[1.883, 0.999, 1.883]} />
      <mesh geometry={nodes.lightLiving.geometry} material={materials.lightbulb} position={[0.88, 11.487, -3.674]} scale={[1.883, 0.999, 1.883]} />
      <mesh geometry={nodes.sensorLiving.geometry} material={materials.sensor} position={[8.759, 8.59, -9.795]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.405, 0.837]} />
      <mesh geometry={nodes.sensorBed.geometry} material={materials.sensor} position={[-4.581, 9.74, -22.772]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.405, 0.837]} />
      <mesh geometry={nodes.sensorBath.geometry} material={materials.sensor} position={[3.439, 9.881, -22.772]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.405, 0.837]} />
      <group position={[18.19, 2.591, -9.058]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve007.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve007_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve007_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve007_3.geometry} material={materials.soil} />
      </group>
      <mesh geometry={nodes.sensorFarm.geometry} material={materials.sensor} position={[14.366, 8.053, -10.674]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 0.405, 0.837]} />
      <group position={[-11.954, 10.509, -6.779]} scale={0.071}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.kitchen4} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.kitchen1} />
      </group>
      <group position={[18.19, 2.591, -12.048]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve009.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve009_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve009_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve009_3.geometry} material={materials.soil} />
      </group>
      <group position={[18.19, 2.591, -15.317]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve010.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve010_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve010_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve010_3.geometry} material={materials.soil} />
      </group>
      <group position={[18.19, 2.591, -18.558]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve011.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve011_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve011_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve011_3.geometry} material={materials.soil} />
      </group>
      <group position={[21.13, 2.591, -18.558]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve012.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve012_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve012_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve012_3.geometry} material={materials.soil} />
      </group>
      <group position={[21.13, 2.591, -15.402]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve013.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve013_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve013_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve013_3.geometry} material={materials.soil} />
      </group>
      <group position={[21.13, 2.591, -12.179]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve014.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve014_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve014_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve014_3.geometry} material={materials.soil} />
      </group>
      <group position={[21.13, 2.591, -8.888]} rotation={[1.334, -0.896, 0.498]}>
        <mesh geometry={nodes.BezierCurve015.geometry} material={materials.tree} />
        <mesh geometry={nodes.BezierCurve015_1.geometry} material={materials.leaf} />
        <mesh geometry={nodes.BezierCurve015_2.geometry} material={materials.pot} />
        <mesh geometry={nodes.BezierCurve015_3.geometry} material={materials.soil} />
      </group>
    </group>
  )
}

useGLTF.preload('/Model1.glb')
